export const USER_WALLET_ADDRESS = "USER_WALLET_ADDRESS";

export const GET_CONTRACT = "GET_CONTRACT";
export const GET_TRONWEB = "GET_TRONWEB";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_FIELD_VALUE = "SER_FIELD_VALUE";
export const SET_REF_ADDRESS = "SET_REF_ADDRESS";

// newly added
export const GET_USER_REF_BACK_PERCENT = "GET_USER_REF_BACK_PERCENT";
export const GET_USER_REFERAL_WITHDRAW = "GET_USER_REFERAL_WITHDRAW";
export const GET_USER_AVAILABLE_BALANCE_WITHDRAWAL = "GET_USER_AVAILABLE_BALANCE_WITHDRAWAL";
export const GET_USER_PERCENT_RATE = "GET_USER_PERCENT_RATE";
export const TOTAL_WITHDRAWAN = "TOTAL_WITHDRAWAN";
export const TOTAL_INVESTED = "TOTAL_INVESTED";
export const GET_CONTRACT_BALANCE = "GET_CONTRACT_BALANCE";
export const GET_USER_DIVIDENDS = "GET_USER_DIVIDENDS";
export const GET_USER_UNILEVEL_BONUS = "GET_USER_UNILEVEL_BONUS";
export const USERS = "USERS";
export const TOTAL_USERS = "TOTAL_USERS";
export const GET_CONTRACT_BONUS = "GET_CONTRACT_BONUS";
export const GET_USER_UNI_LVL_BONUS = "GET_USER_UNI_LVL_BONUS";
export const GET_CONTRACT_BALANCE_RATE = "GET_CONTRACT_BALANCE_RATE";
export const GET_USER_AMOUNT_OF_DEPOSITS = "GET_USER_AMOUNT_OF_DEPOSITS";
export const GET_USER_DOWNLINE_COUNT = "GET_USER_DOWNLINE_COUNT";
export const GET_USER_UNI_LEVEL_AMOUNT = "GET_USER_UNI_LEVEL_AMOUNT";

export const GET_USER_TOTAL_DEPOSITS = "GET_USER_TOTAL_DEPOSITS";
export const GET_USER_REFERRAL_BONUS = "GET_USER_REFERRAL_BONUS";
export const BASE_PERCENT = "BASE_PERCENT";
export const WALLET_BALANCE = "WALLET_BALANCE";
export const GET_USER_REFERRER = "GET_USER_REFERRER";
export const GET_REF_INC = "GET_REF_INC";
export const GET_USER_TOTAL_WITHDRAW = "GET_USER_TOTAL_WITHDRAW";
