export const tabsData = {
  secondTab: [
    {
      id: "panel1bh-header",
      areaControl: "panel1bh-content",
      panel: "panel1",
      header: "Do i need to invest to earn referrers commissions ?",
      description: "Yes minimum investment is required 1000 TRX to register you on blockchain smart contract to receive your commissions",
    },
    {
      id: "panel2bh-header",
      areaControl: "panel2bh-content",
      panel: "panel2",
      header: "How I can invite friends ?",
      description: "You can find your referral link in your wallet statistics and share it with your friends.",
    },
    {
      id: "panel3bh-header",
      areaControl: "panel3bh-content",
      panel: "panel3",
      header: "What I get when I share my referral link ?",
      description: "You receive commissions from each deposit depending on referral level.",
    },
    {
      id: "panel4bh-header",
      areaControl: "panel4bh-content",
      panel: "panel4",
      header: "What I must do to start earning with referrals?",
      description: "You need to make at least 1000 TRX deposit to unlock the referral system.",
    },
    {
      id: "panel5bh-header",
      areaControl: "panel5bh-content",
      panel: "panel5",
      header: "How many referral levels are on CRYPTOBANK ?",
      description: "There are 4 LVL referral system. Referral commissions are 5%/2%/0.5%/0.5%",
    },
    {
      id: "panel6bh-header",
      areaControl: "panel6bh-content",
      panel: "panel6",
      header: "Where i can find promotion materials?",
      description: "Promotion materials you can find in our site by clicking on button 'Promo Materials'",
    },
  ],
  firstTab: [
    {
      id: "panel7bh-header",
      areaControl: "panel7bh-content",
      panel: "panel7",
      header: "What is Smart-Contract ?",
      description: `A smart contract is a self-executing contract with the terms of the agreement between buyer and seller being directly written
      into lines of code. The code and the agreements contained therein exist across a distributed, decentralized blockchain
      network. The code controls the execution, and transactions are trackable and irreversible. Smart contracts permit trusted
      transactions and agreements to be carried out among disparate, anonymous parties without the need for a central authority,
      legal system, or external enforcement mechanism.`,
    },
    {
      id: "panel8bh-header",
      areaControl: "panel8bh-content",
      panel: "panel8",
      header: "Why I should trust CRYPTOBANK ?",
      description: "CRYPTOBANK is verified & audited smart contract with transparent contract.",
    },
    {
      id: "panel9bh-header",
      areaControl: "panel9bh-content",
      panel: "panel9",
      header: "Why i should choose CRYPTOBANK?",
      description: "CRYPTOBANK contract offers you earn up to 200% of your deposit and offers you extra referral bonuses.",
    },
    {
      id: "panel10bh-header",
      areaControl: "panel10bh-content",
      panel: "panel10",
      header: "Who is controlling funds on CRYPTOBANK?",
      description: "No one has access to control funds over CRYPTOBANK all payouts are made on blockchain smart contract.",
    },
    {
      id: "panel11bh-header",
      areaControl: "panel11bh-content",
      panel: "panel11",
      header: "Do you have a smart-contract audit ?",
      description: "Yes our contract is audited by smartaudit.services.",
    },
    {
      id: "panel12bh-header",
      areaControl: "panel12bh-content",
      panel: "panel12",
      header: "How I can get support ?",
      description: "ou can get support on official telegram groups or using email admin@CRYPTOBANK.com",
    },
  ],
  thirdTab: [
    {
      id: "panel13bh-header",
      areaControl: "panel13bh-content",
      panel: "panel13",
      // header: "What is an incentive bonus ?",
      // description: "You receive extra daily percent for your deposit earnings when your total direct referrals investments reach certain points",
    },
    {
      id: "panel14bh-header",
      areaControl: "panel14bh-content",
      panel: "panel14",
      // header: "How do i get an incentive bonus ?",
      // description: "You receive extra daily percent for your deposit earnings when your total direct referrals investments reach certain points",
    },
    {
      id: "panel15bh-header",
      areaControl: "panel15bh-content",
      panel: "panel15",
      // header: "Do all referral levels are counted in incentive bonus ?",
      // description: "No only direct referrals are counted (LVL 1)",
    },
  ],
  forthTab: [
    {
      id: "panel16bh-header",
      areaControl: "panel16bh-content",
      panel: "panel16",
      header: "How referral pool works ?",
      description: "From each deposit 1% go to the referral pool. When referral pool reach 100,000 TRX prizes are sent out to top 10 referrals",
    },
    {
      id: "panel17bh-header",
      areaControl: "panel17bh-content",
      panel: "panel17",
      header: "What are prizes ?",
      description: "Top 10 of monoline unilevel rewards 0.05% - 0.05% - 0.05% - 0.05% - 0.05% - 0.05% - 0.05% - 0.05% - 0.05% - 0.05% ",
    },
    {
      id: "panel18bh-header",
      areaControl: "panel18bh-content",
      panel: "panel18",
      header: "When prizes are sent out ?",
      description: "Prizes are sent out automatically as pool reach 100,000 TRX",
    },
    {
      id: "panel19bh-header",
      areaControl: "panel19bh-content",
      panel: "panel19",
      header: "How many times I can join the referral pool?",
      description: "There are no limits how many times you can participate in referral pool.",
    },
  ],
  fifthTab: [
    {
      id: "panel20bh-header",
      areaControl: "panel20bh-content",
      panel: "panel20",
      header: "What are minimum and maximum deposit amount ?",
      description: "Minimum deposit amount is 1000 TRX. Maximum deposit amount is 1,000,000 TRX per wallet",
    },
    {
      id: "panel21bh-header",
      areaControl: "panel21bh-content",
      panel: "panel21",
      header: "How I can invite friends ?",
      description: "You need a Tron Wallet extension or use Tron Mobile wallet that supports DAPP browser.",
    },
    {
      id: "panel22bh-header",
      areaControl: "panel22bh-content",
      panel: "panel22",
      header: "How I can get TRX ?",
      description: "You can get TRX on popular cryptocurrency exchanger services.",
    },
    {
      id: "panel23bh-header",
      areaControl: "panel23bh-content",
      panel: "panel23",
      header: "Is there a limit how many deposits I can make ?",
      description: "Maximum you can make 200 deposits per wallet",
    },
    {
      id: "panel24bh-header",
      areaControl: "panel24bh-content",
      panel: "panel24",
      header: "What is Basic bonus ?",
      description: "Basic bonus is percentage of daily earnings that contract started at.",
    },
    {
      id: "panel25bh-header",
      areaControl: "panel25bh-content",
      panel: "panel25",
      // header: "What is Hold bonus ?",
      // description: "For each 10 days without withdrawal you earn +0.1% max 0.3% Hold bonus. Hold bonus is limited to 2%.",
    },
    {
      id: "panel26bh-header",
      areaControl: "panel26bh-content",
      panel: "panel26",
      header: "What is active user bonus ?",
      description: `For each 1000 participants on smart-contract active user bonus increase for 0.01% max 1%. Active user bonus is limited to 4%. Once you
      have made withdrawal before reaching 320% active user bonus is no longer available for you.`,
    },
    {
      id: "panel27bh-header",
      areaControl: "panel27bh-content",
      panel: "panel27",
      // header: "What is an incentive bonus ?",
      // description: "When your referrals invest at least 1,000 TRX you unlock the first incentive bonus total you can get up to 1% Incentive bonus.",
    },
    {
      id: "panel28bh-header",
      areaControl: "panel28bh-content",
      panel: "panel28",
      header: "How I can make withdrawal ?",
      description: "You can withdraw your funds by clicking “Withdraw Money” button. ",
    },
    {
      id: "panel29bh-header",
      areaControl: "panel29bh-content",
      panel: "panel29",
      header: "What time I can withdraw earnings ?",
      description: "You can withdraw once per 24H. All earnings are realtime.",
    },
    {
      id: "panel30bh-header",
      areaControl: "panel30bh-content",
      panel: "panel30",
      header: "What is the maximum percentage that I can have?",
      description: "You can withdraw once per 24H. All earnings are realtime.",
    },
  ],
};
